version: "3"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "${PG_PORT}:5432"  
    volumes:
      - ./ny_taxi_pg_data:/var/lib/postgresql/data
