version: "3"

services:
dbt_postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: "orders"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - postgresdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
