version: 2

sources:

    - name: orders
      schema: public
      tags: ["orders"]
      description: "source data"

      tables:
        - name: orders
          description: "Orders data"
          identifier: orders
          # columns:
          #   - name: postal_code
          #     description: ""
          #     tests:
          #       - not_null
