version: "3.9"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"  
    volumes:
      - ./ny_taxi_pg_data:/var/lib/postgresql/data
