jitsu_lab:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      user: admin
      password: clickhouse
      port: 8443
      host: rc1b-vluip6m6mbnv570v.mdb.yandexcloud.net
      retries: 1
      verify: False
      secure: True
      connect_timeout: 10
