ny_taxi:
  target: dev
  outputs:
    dev:
      type: postgres
      host: de_postgres
      user: root
      password: root
      port: 5432
      dbname: ny_taxi 
      schema: public
      threads: 1
      connect_timeout: 10 
      