name: 'superstore'
version: '1.0.0'
config-version: 2

profile: 'superstore'

model-paths: ["models"]
test-paths: ["tests"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  superstore:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: table
