superstore:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin 
      password: admin
      port: 5432
      dbname: orders 
      schema: default
      threads: 4
      connect_timeout: 10 
     