superstore:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin
      password: admin
      port: 5432
      dbname: orders # or database instead of dbname
      schema: public
      threads: 1   
      connect_timeout: 10 # default 10 seconds
      